/**:
  controller_manager:
    ros__parameters:
      update_rate: 500  # Hz
      # is_async: true
          
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster
      template_ros2_controller:
        type: tita_locomotion/TemplateRos2Controller
      effort_controller:
        type: effort_controllers/JointGroupEffortController
      position_controller:
        type: position_controllers/JointGroupPositionController
      pid_controller:
        type: pid_controller/PidController  # 新增的 PID 控制器
       
  
  imu_sensor_broadcaster:
    ros__parameters:
      update_rate: 500  # Hz
      sensor_name: imu
      frame_id:  imu

  joint_state_broadcaster:
    ros__parameters:
      update_rate: 500  # Hz
      
  template_ros2_controller:
    ros__parameters:
      update_rate: 500  # Hz
      joints:
        - joint_left_leg_1
        - joint_left_leg_2
        - joint_left_leg_3
        - joint_right_leg_1
        - joint_right_leg_2
        - joint_right_leg_3
      command_interfaces:
        - position
        - velocity
        - effort
        - kp
        - kd
      state_interfaces:
        - position
        - velocity
        - effort
      sensors:
        - imu
  
  effort_controller:
    ros__parameters:
      joints:
        - joint_left_leg_1
        - joint_left_leg_2
        - joint_left_leg_3
        # - joint_left_leg_4
        - joint_right_leg_1
        - joint_right_leg_2
        - joint_right_leg_3
        # - joint_right_leg_4
  
  position_controller:
    ros__parameters:
      joints:
        - joint_left_leg_1
        - joint_left_leg_2
        - joint_left_leg_3
        # - joint_left_leg_4
        - joint_right_leg_1
        - joint_right_leg_2
        - joint_right_leg_3
        # - joint_right_leg_4
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
        - effort
        
  pid_controller:
    ros__parameters:
      dof_names: 
        - joint_left_leg_1
        - joint_left_leg_2
        - joint_left_leg_3
        - joint_right_leg_1
        - joint_right_leg_2
        - joint_right_leg_3
      command_interface: effort
      reference_and_state_interfaces: ["position"]
      gains:
        joint_left_leg_1: {p: 80.0, i: 0.0, d: 1.5, i_clamp_max: 5.0, i_clamp_min: -5.0}
        joint_left_leg_2: {p: 80.0, i: 0.0, d: 1.5, i_clamp_max: 5.0, i_clamp_min: -5.0}
        joint_left_leg_3: {p: 80.0, i: 0.0, d: 1.5, i_clamp_max: 5.0, i_clamp_min: -5.0}
        joint_right_leg_1: {p: 80.0, i: 0.0, d: 1.5, i_clamp_max: 5.0, i_clamp_min: -5.0}
        joint_right_leg_2: {p: 80.0, i: 0.0, d: 1.5, i_clamp_max: 5.0, i_clamp_min: -5.0}
        joint_right_leg_3: {p: 80.0, i: 0.0, d: 1.5, i_clamp_max: 5.0, i_clamp_min: -5.0}
